In [9]:
import pandas as pd

另外可以導入Series和DataFrame，因為這兩個經常被用到：

In [10]:
from pandas import Series, DataFrame

# 5.1 Introduction to pandas Data Structures

資料結構其實就是Series和DataFrame。

# 1 Series

這裡series我就不翻譯成序列了，因為之前的所有筆記裡，我都是把sequence翻譯成序列的。

series是一個像陣列一樣的一維序列，並伴有一個陣列表示label，叫做index。創建一個series的方法也很簡單：

In [11]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

可以看到，左邊表示index，右邊表示對應的value。可以通過value和index屬性查看：

In [12]:
obj.values

array([ 4,  7, -5,  3])

In [13]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

當然我們也可以自己指定index的label：

In [14]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [15]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

可以用index的label來選擇：

In [17]:
obj2['a']

-5

In [18]:
obj2['d'] = 6

In [19]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

這裡['c', 'a', 'd']其實被當做了索引，儘管這個索引是用string構成的。

使用numpy函數或類似的操作，會保留index-value的關係：

In [20]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [21]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [22]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

另一種看待series的方法，它是一個長度固定，有順序的dict，從index映射到value。在很多場景下，可以當做dict來用：

In [23]:
'b' in obj2

True

In [24]:
'e' in obj2

False

還可以直接用現有的dict來創建series：

In [25]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}

In [26]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

series中的index其實就是dict中排好序的keys。我們也可以傳入一個自己想要的順序：

In [27]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [28]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

順序是按states裡來的，但因為沒有找到california,所以是NaN。NaN表示缺失資料，用之後我們提到的話就用missing或NA來指代。pandas中的isnull和notnull函數可以用來檢測缺失資料：

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

series也有對應的方法：

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

關於缺失資料，在第七章還會講得更詳細一些。

series中一個有用的特色自動按index label來排序（Data alignment features）：

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

這個Data alignment features（資料對齊特色）和資料庫中的join相似。

serice自身和它的index都有一個叫name的屬性，這個能和其他pandas的函數進行整合：

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

series的index能被直接更改：

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# 2 DataFrame

DataFrame表示一個長方形表格，並包含排好序的列，每一列都可以是不同的數數值型別（數位，字串，布林值）。DataFrame有行索引和列索引（row index, column index）；可以看做是分享所有索引的由series組成的字典。資料是保存在一維以上的區塊裡的。

（其實我是把dataframe當做excel裡的那種表格來用的，這樣感覺更直觀一些）

構建一個dataframe的方法，用一個dcit，dict裡的值是list：



In [40]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

dataframe也會像series一樣，自動給資料賦index, 而列則會按順序排好。

對於一個較大的DataFrame，用head方法會返回前5行（注：這個函數在資料分析中經常使用，用來查看表格裡有什麼東西）：

In [41]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

如果指定一列的話，會自動按列排序：

In [42]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

如果你導入一個不存在的列名，那麼會顯示為缺失資料：

In [43]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

In [44]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

從DataFrame裡提取一列的話會返回series格式，可以以屬性或是dict一樣的形式來提取：

In [46]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [47]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

注意：frame2[column]能應對任何列名，但frame2.column的情況下，列名必須是有效的python變數名才行。

返回的series有DataFrame種同樣的index，而且name屬性也是對應的。

對於行，要用在loc屬性裡用 位置或名字：

In [48]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

列值也能通過賦值改變。比如給debt賦值：

In [49]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [50]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

如果把list或array賦給column的話，長度必須符合DataFrame的長度。如果把一二series賦給DataFrame，會按DataFrame的index來賦值，不夠的地方用缺失資料來表示：

In [51]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

如果列不存在，賦值會創建一個新列。而del也能像刪除字典關鍵字一樣，刪除列：

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

然後用del刪除這一列：

In [53]:
del frame2['eastern']

In [54]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

注意：columns返回的是一個view，而不是新建了一個copy。因此，任何對series的改變，會反映在DataFrame上。除非我們用copy方法來新建一個。

另一種常見的格式是dict中的dict：

In [55]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

把上面這種嵌套dcit傳給DataFrame，pandas會把外層dcit的key當做列，內層key當做行索引：

In [56]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

另外DataFrame也可以向numpy陣列一樣做轉置：

In [57]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

指定index：

In [58]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

series組成的dict：

In [59]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [60]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

其他一些可以傳遞給DataFrame的構造器：

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/yv7rc.png)

如果DataFrame的index和column有自己的name屬性，也會被顯示：



In [61]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [69]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

values屬性會返回二維陣列：

In [63]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

如果column有不同的類型，dtype會適應所有的列：

In [64]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# 3 Index Objects (索引物件)

pandas的Index Objects (索引物件)負責保存axis labels和其他一些資料（比如axis name或names）。一個陣列或其他一個序列標籤，只要被用來做構建series或DataFrame，就會被自動轉變為index：

In [65]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [66]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [67]:
index[1:]

Index(['b', 'c'], dtype='object')

index object是不可更改的：

In [68]:
index[1] = 'd'

TypeError: ignored

正因為不可修改，所以data structure中分享index object是很安全的：

In [ ]:
labels = pd.Index(np.arange(3))
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

In [ ]:
obj2.index is labels

index除了想陣列，還能像大小一定的set：

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
'Ohio' in frame3.columns

In [ ]:
2003 in frame3.columns

與python裡的set不同，pandas的index可以有重複的labels：

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

在這種重複的標籤中選擇的話，會選中所有相同的標籤。

Index還有一些方法和屬性：

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/14j6g.png)
